version: 2
jobs:
  build:
    docker:
      - image: node:10.12
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile

      - run:
          name: Lint
          command: yarn run lint

      - run:
          name: Test
          command: yarn run test

      - run:
          name: Codecov
          command: yarn run codecov

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
