version: 2

defaults: &defaults
  docker:
    - image: node:10.13.0
  working_directory: /repo

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: yarn run test
      - run:
          name: Codecov
          command: yarn run codecov
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: /repo
          paths:
            - ./node_modules

  prepare_gcp:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: /repo
    steps:
      - checkout
      - run:
          name: Decode credential
          command: echo $GCLOUD_SERVICE_KEY | base64 -d > ./secret.json
      - run:
          name: Activate service account
          command: |
            gcloud auth activate-service-account --key-file=./secret.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
      - persist_to_workspace:
          root: /repo
          paths:
            - ./secret.json

  regression:
    docker:
      - image: andoshin11/node-xcb:10.13.0
    working_directory: /repo
    steps:
      - checkout
      - attach_workspace:
          at: /repo
      - run:
          name: Screenshot
          command: yarn run screenshot
      - run:
          name: reg-suit
          command: GOOGLE_APPLICATION_CREDENTIALS=./secret.json yarn run reg-suit
      - run:
          name: Clean up
          command: rm ./secret.json

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
      - prepare_gcp
      - regression:
          requires:
            - test
            - prepare_gcp
